version: '3.8'

services:
  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - .:/var/www/html
      - logs_volume:/var/www/html/logs
    depends_on:
      mysql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    # We need to replace those values in the pipeline for production environment
    # environment:
    #   - DB_HOST=mysql
    #   - DB_PORT=3306
    #   - DB_NAME=stock_app
    #   - DB_USERNAME=stock_user
    #   - DB_PASSWORD=stock_password
    #   - RMQ_ENABLED=0
    #   - RMQ_HOST=rabbitmq
    #   - RMQ_VHOST=/
    #   - RMQ_PORT=5672
    #   - RMQ_USERNAME=guest
    #   - RMQ_PASSWORD=guest
    networks:
      - app-network

  # Nginx Web Server
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: stock_app
      MYSQL_USER: stock_user
      MYSQL_PASSWORD: stock_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
      
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:
  logs_volume: